fixing s2i *.cdd issue

diff --git a/cloud/docker/lib/run b/cloud/docker/lib/run
--- a/cloud/docker/lib/run
+++ b/cloud/docker/lib/run
@@ -118,7 +118,15 @@ else
   		exit
 	else
 		if [ "$CDD_FILE" = "/opt/tibco/be/application/dummy.txt" ]; then
-				CDD_FILE="/opt/tibco/be/application/*.cdd"
+			#Check App location have cdd or not
+			CDD_LOCATION="/opt/tibco/be/application"
+			cdds=$(find $CDD_LOCATION -name "*.cdd")
+			cddCnt=$(find $CDD_LOCATION -name "*.cdd" | wc -l)
+			if [ $cddCnt -ne 1 ]; then
+				printf "ERROR: The directory - $CDD_LOCATION must have single CDD file\n"
+				exit 1
+			fi
+			CDD_FILE=${cdds[0]}
 		fi
 	fi
 	if [ "$EAR_FILE" = "no-default" ]; then
@@ -126,7 +134,15 @@ else
   		exit
 	else
 		if [ "$EAR_FILE" = "/opt/tibco/be/application/ear/dummy.txt" ]; then
-				EAR_FILE="/opt/tibco/be/application/ear/*.ear"
+			#Check App location have ear or not
+			EAR_LOCATION="/opt/tibco/be/application/ear"
+			ears=$(find $EAR_LOCATION -name "*.ear")
+			earCnt=$(find $EAR_LOCATION -name "*.ear" | wc -l)
+			if [ $earCnt -ne 1 ]; then
+				printf "ERROR: The directory - $EAR_LOCATION must have single EAR file\n"
+				exit 1
+			fi
+			EAR_FILE=${ears[0]}
 		fi
 	fi
 
