added s2i build check up for building app image

diff --git a/cloud/docker/build/assemble b/cloud/docker/build/assemble
--- a/cloud/docker/build/assemble
+++ b/cloud/docker/build/assemble
@@ -13,3 +13,23 @@ mkdir -p /opt/tibco/be/application/ear
 
 cp -R /tmp/src/*.ear /opt/tibco/be/application/ear
 rm /opt/tibco/be/application/*.ear
+
+if [ -e "/opt/tibco/be/application/dummy.txt" ]; then
+    #Check App location have cdd or not
+    CDD_LOCATION="/opt/tibco/be/application"
+    cddCnt=$(find $CDD_LOCATION -name "*.cdd" | wc -l)
+    if [ $cddCnt -ne 1 ]; then
+        printf "ERROR: The given application location must have single CDD file\n"
+        exit 1
+    fi
+fi
+
+if [ -e "/opt/tibco/be/application/ear/dummy.txt" ]; then
+    #Check App location have ear or not
+    EAR_LOCATION="/opt/tibco/be/application/ear"
+    earCnt=$(find $EAR_LOCATION -name "*.ear" | wc -l)
+    if [ $earCnt -ne 1 ]; then
+        printf "ERROR: The given application location must have single EAR file\n"
+        exit 1
+    fi
+fi
